### ISSUE TITLE
Change emojis to EmojiTwo

### ISSUE THREAD

**Issue by Flohack74** [ubports/keyboard-component#1]
Seems our Emojis are no longer open source, needs a change. Proposed solution is to use https://github.com/EmojiTwo

**Comment by Aurnytoraink** [comment]
I know that this is an old issues but this is still not closed so this is why I kind of reopen the project.

So as now Emojyone uses a priority license, maybe we can switch to these emojis:
https://openmoji.org/

**Comment by mateosalta** [comment]
there is also https://twemoji.twitter.com/ seems up to date, and opensource licensing

and we really need updated from the old set (it has some smiles that are really different when using to communicate ☺️🤗 these show as blush and hands out, but on ut - they are a big smile, and hugging - arms wrapped)

**Comment by mateosalta** [comment]
unfortunately, the general move is towards the SVGinOT format for emoji - in qt this is falling back to the b/w outlines on twemoji - it has a nearly complete list of emoji though - I found someone that packaged v11 as SBIX (this is the format for the fonts I think is the only color one working in browser/qt) but it is missing many

**Comment by peat-psuwit** [comment]
Migrated to GitLab
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/1
