### ISSUE TITLE
Typing bug. More pronounced on Facebook when 'mentioning' a person. Also a backspace issue.

### ISSUE THREAD

**Issue by Flohack74** [ubports/keyboard-component#10]
_From @tenleftfingers on June 22, 2017 12:34_

I've noticed two problems when typing. It happens most on Facebook via the browser but I've also seen similar in the standard messaging app and other apps that accept text input.

It's hard to describe, so I'll leave a video at this link for now and try to keep it until the bug is closed.
https://www.dropbox.com/s/mvy8osp95isusrh/ut-typing-bug.mp4?dl=0

1: In FB when I mention someone (blue text appears) and press space, rubbish text is appended (always a part of their name). Sometimes waiting a few seconds before pressing space helps.
2: When I backspace, it takes away too much including the friends name I mentioned. Repeating the process doesn't help either and the problem has no workaround I can find.

This is the single biggest annoyance with Ubuntu Touch at the moment for me. It's not just a Facebook issue, but it's the one I remember and can reproduce the easiest. The backspace problem has happened to me when text messaging too where it became impossible to type certain things.

Aquaris E4.5.
Canonical OTA-15.

_Copied from original issue: ubports/ubports-touch#125_

**Comment by Flohack74** [comment]
I will transfer this to the keyboard component, we got separate trackers for those things ;)

**Comment by balcy** [comment]
I think this the same issue:
https://github.com/ubports/oxide/issues/1

The current suggestion (above the letter q) is not cleared when changing the cursor or inserting text like in the mention. In your video  you can also see, that the inserted text is the current keyboard suggestion.

**Comment by balcy** [comment]
at least for point 1.

**Comment by giiba** [comment]
I think this has to do with the interaction between the Keyboard, QtWebengine, and html text boxes.

I have only been able to correct the issue in one place: www.mu43.com. The default setting on the site's text entry is a rich text entry field which behaves as others have noted. However if I turn off the rich text feature suddenly the keyboard works as expected and there is no problem. Turn it on and the problems return.

I use the site through a simple web app (morph based) but the behaviour is the same in app or browser. I don't know what software is used for the site.

**Comment by kugiigi** [comment]
This was way back when Oxide is used right? I guess this isn't valid anymore?

**Comment by peat-psuwit** [comment]
Migrated to GitLab
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/10
