### ISSUE TITLE
Make the 'Advanced text functions' known with an icon

### ISSUE THREAD

**Issue by Mondane** [ubports/keyboard-component#103]
From the OTA-11 release notes:

> *Your keyboard, now smarter*
> Kugi has outdone himself this time. With this update you'll find a new way to edit text via the Ubuntu Touch on-screen keyboard: the Advanced Text Functions. Using this feature, you can move around your typed text, undo and redo actions, move around a text selection rectangle, and use the cut/copy/paste commands, all from the same overlay. To get started, press and hold the space bar!
>
> We are still unsure about the discoverability of this feature, so stay tuned for changes that will make it even easier to find and use!

About that last sentence, why not add an icon the the space bar as is done for e.g. the accents etc. A sketch from Telegram made by YougoChats based on my explanation:

![image](https://user-images.githubusercontent.com/1150272/67621212-82406680-f80e-11e9-9dc6-df195545ac24.png)

**Comment by SanderKlootwijk** [comment]
Great idea! Here's a quick design example (I've used the edit.svg file from the Suru icons).

![afbeelding](https://user-images.githubusercontent.com/12654277/67634887-706bcb80-f8c1-11e9-903b-179862a6043d.png)

**Comment by Flohack74** [comment]
Greast idea, the only problem I am afraid of is that we need to patch this in _all_ keyboards since the icons are drawn based on the key definitions per custom keyboard. If we find a way to do it in a common base class then I think it would work.

**Comment by UniversalSuperBox** [comment]
Nah, it's all one key: https://github.com/ubports/keyboard-component/blob/xenial/qml/keys/SpaceKey.qml

**Comment by UniversalSuperBox** [comment]
An alternative to this was merged in https://github.com/ubports/keyboard-component/pull/98
