### ISSUE TITLE
anchor loop warning in maliit-server.log

### ISSUE THREAD

**Issue by lduboeuf** [ubports/keyboard-component#105]
don't know precisely when it occurs but see one of repeatingly  logs :
WARNiNG: file:///usr/share/maliit/plugins/com/ubuntu/keys/Magnifier.qml:50:5: QML Rectangle: Possible anchor loop detected on centerIn.

**Comment by Fuseteam** [comment]
do you still see this log?

**Comment by lduboeuf** [comment]
yes on devel

**Comment by Flohack74** [comment]
UT´s application logs are full of binding loops and such things. Its a shame how few developers care about fixing that, as soon as it works its shipped.

**Comment by Fuseteam** [comment]
hmm where do you see these logs? i checked in magnifier.qml but i can't identify what's causing the loop

**Comment by Fuseteam** [comment]
hmmmm it seems related to #82

**Comment by Fuseteam** [comment]
what are these binding loops anyway?

**Comment by Flohack74** [comment]
See http://blog.davidedmundson.co.uk/blog/daves-qml-binding-loop-backtrace-printer/

**Comment by Fuseteam** [comment]
thanks

**Comment by lduboeuf** [comment]
Duplicate of https://github.com/ubports/keyboard-component/issues/82
