### ISSUE TITLE
Keyboard autocorrection improvals

### ISSUE THREAD

**Issue by ruedigerkupper** [ubports/keyboard-component#106]
### Description of the feature
Intelligent autocorrection while typing

### Illustrations
Ever since I've been using Ubuntu Touch (and it's the only Smartphone OS I#ve ever used, so please don't expect me to know anything about Android or iOS) I've been wondering why autocerrection is so bad. It almost never does help me in tyyping, instead, it appears to be constantly in my way. I have not disabled it, though, because I think it should be improving user experience on the phone – but really, it does not at this time.

Autocorrection on Ubuntu phone seems to be completely context-igrnorant (please correct me, if I'm wrong). Human language is stongly context dependant. Any character typed has certain characters that are more or less likely following. The autocorrection must obviously choose the most likely character for autocompletion. The same holds true for words: The beginning of a sentance very strongly determmines possible endlings. The autocorrection must suggest words that complete the sentence in a sensible way.

Using Ubuntu Phone / Ubuntu Tocuh / UBports I've always had the impression that none of these correlations are used at all for autocorrection? (Please comment, if you are a developer.)

This feature suggestion is about using well-known correlations in characters and words for improving autocorrection.

I'd expect that established OSes (The G-type and the A-type) have done tzzhis form tzhe start (as said above, I never tried them, but I honestly cannot imagine anything other).

Please improve autocorection an Ubuntu Touch to a state where it starts to begin getting userful -- it's rather annoying at this time.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/106

Sorry for your inconvenience.
