### ISSUE TITLE
Keyboard does not allow all layouts without external keyboard

### ISSUE THREAD

**Issue by Flohack74** [ubports/keyboard-component#11]
_From @TheLastProject on June 29, 2017 19:22_

This is more a feature request than a bug I suppose, but one thing that always bothered me is that I can't set my tablet's OSK to English Dvorak, but I can use it with an external keyboard. It would be great if this was more consistent and I could use all layouts everywhere.

_Copied from original issue: ubports/ubports-touch#140_

**Comment by Fuseteam** [comment]
dvorak was merged with #86 what layouts are still missing?

**Comment by Flohack74** [comment]
No idea lets close this :)
