### ISSUE TITLE
swiping up from the top row dismisses the keyboard partially

### ISSUE THREAD

**Issue by Fuseteam** [ubports/keyboard-component#111]
swiping up from the top row dismisses the osk partially
this is rather annoying for flick keyboards( #93 ), but it is also rather difficult to reproduce reliably
the only way i have been able to reproduce this reliably is by opening the osk in portrait and rotating the phone to landscape
it also happens in portrait occasionally but i have not been able to reproduce it
any help finding the files responsible for swipe to dismiss is welcome

**Comment by Fuseteam** [comment]
this may or may not be related to #42 further research needed

**Comment by cibersheep** [comment]
Hello.
- Is this still an issue?
- Is «top row» the indicators bar?
- Could you add steps to reproduce?

Thanks

**Comment by Fuseteam** [comment]
yes it is still an issue
the <top row> the top row of the keyboard
it is rather difficult to reproduce but one way is to do the following
1. open the keyboard by say going in a telegram group
2. while the keyboard is up rotate you device
3. swipe up from say the q

notes:
this problem is much more annoying in with flick keyboards like the japanese layout
it also happens sometimes without rotating but i have not been able to figure out how to trigger it
disabling autocomplete seems to workaround the issue

**Comment by cibersheep** [comment]
- I have selected Japanese keyboard and try to reproduce. Tried rotate the device with OSK visible:
  - swiping up from different character in Japanese keyboard
  - swiping down to dismiss keyboard

- I have also tried in Catalan keyboard (rotating the device with OSK visible):
  - selecting 1 from q (swiping up, even if it's not needed)
  - Tried to dismissing keyboard swiping down.

I couldn't reproduce on Arale Dev channel. More investigation is needed I guess

**Comment by Fuseteam** [comment]
even rotating while the osk is open didn't reproduce it?
dang this one is difficult te reproduce :v

**Comment by cibersheep** [comment]
> even rotating while the osk is open didn't reproduce it?
> dang this one is difficult te reproduce :v

I forgot to mention that in all cases I had the OSK up and rotated the device a couple of times

**Comment by Fuseteam** [comment]
@cibersheep did you swipe up from the actual charkeys? like say the q on the standard qwerty keyboard
not unlike how you type "c" on the japanese keyboard
ah perhaps i should also mention the osk should be up in portrait then you rotate to landscape while it's up before swiping up from one of the top row of keys
at least spellcheck should also be enabled

**Comment by cibersheep** [comment]
Oooook... it took a while but I was able to reproduce :)

Steps to reproduce:
- tap and hold a character from the keyboard (one fro the top row is easier)
- before the extended keyboard shows / gets the focus, swipe to the top side of the keyboard
- swipe down

Touch is capture for the keyboard dismiss Touch area


![keyb2](https://user-images.githubusercontent.com/6640041/80161913-1e86d280-85d2-11ea-8cad-616a03ba78e3.gif)

Full video:

[keyboard-video-mp4.zip](https://github.com/ubports/keyboard-component/files/4525461/keyboard-video-mp4.zip)

**Comment by Fuseteam** [comment]
finally someone manageed to reproduce it :joy:

**Comment by Fuseteam** [comment]
wait that just looks like the regular gesture to dismiss the keyboard :thinking:

**Comment by cibersheep** [comment]
> wait that just looks like the regular gesture to dismiss the keyboard thinking

I'm pressing y but what happens is the touch goes to the dismiss keyboard area (I suspect)

**Comment by Fuseteam** [comment]
ohw your just pressing y, yeah that's the weird behavior, turn autocorrect off seems to word around the issue fwiw

**Comment by cibersheep** [comment]
I have autocorrect off, only word suggestion. Is the same behaviour with it on or with all language aids off (top ribbon with suggested words not visible).

**Comment by Fuseteam** [comment]
yes i mean turning word suggestion off

**Comment by Fuseteam** [comment]
i found these logs by running maliit-server with `MALIIT_DEBUG=true`

```
DEBUG: Updating input method area to QRegion(0,623 1280x46)
DEBUG: keyboard is reporting <x y w h>: < 0 623 1280 46 > to the app manager.
DEBUG: Updating input method area to QRegion(0,603 1280x66)
DEBUG: keyboard is reporting <x y w h>: < 0 603 1280 66 > to the app manager.
DEBUG: Updating input method area to QRegion(0,586 1280x83)
DEBUG: keyboard is reporting <x y w h>: < 0 586 1280 83 > to the app manager.
DEBUG: Updating input method area to QRegion(0,570 1280x99)
DEBUG: keyboard is reporting <x y w h>: < 0 570 1280 99 > to the app manager.
```

it looks suspiciously similar to the logs it spews when actually dismissing the keyboard

**Comment by Fuseteam** [comment]
considering it looks suspicously like what it logs when dismissing the keyboard i grep the repo for `keyboard is reporting` and found it only leads to https://github.com/ubports/keyboard-component/blob/ed3c5fbf2a820f194ed2172e8ad2fd729bd4a3b9/src/plugin/inputmethod.cpp#L632-L653

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/111

Sorry for your inconvenience.
