### ISSUE TITLE
auto correct steals blank from entered text

### ISSUE THREAD

**Issue by dbdb78** [ubports/keyboard-component#113]
Hey! My first bug report coming up.

Issue in the ubports native Notes app

Using Swedish version ("Anteckningar"), probably doesn't matter but I have swedish, english and emojies. Disabling Swedish produces the same error. 
I am not connected to Evernote, only using local mode.

What I want to happen: In a note. When I type a sentence and end it with a period (.) and change my mind pressing backspace. I want just the period to disappear. (Pretty straight forward)

What does happen: Sometimes, the period disappers along with the space introducing the word that was "attached" to the period.  I think an example is needed for this to be understood :)

"The cat has nine lives."    
Erasing the period here gives me:
"The cat has ninelives" 

It does not happen all the time. More often in larger files (though not that large, maybe 20-30 sentences). I haven't found the pattern yet on when it appears, maybe some one else has experienced the same stuff?

System: Notes v 0.10.0
OS: 16.04 (OTA-11)

**Comment by ruedigerkupper** [comment]
I confirm that I have met this issue many times and that it is annoying. Not sure when I have seen it the last time, but I believe it is not fixed.
Currently, autocorrect is not working at all in many places antway...

**Comment by ruedigerkupper** [comment]
Just confirmed this long-standing bug is still present just like the OP described.
Steps to reproduce:
- open notes app
- start a new note
- type a space or newline character at the start of the new note
- type some words followed by a full stop, like "one two three."
- delete the full stop by tapping the backspace key
- observe that the space between the last two words gets eaten up

Would be a real imrovement if this could be fixed.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/113

Sorry for your inconvenience.
