### ISSUE TITLE
Is that possible to implement the SWYPE feature?

### ISSUE THREAD

**Issue by Thieb67k** [ubports/keyboard-component#118]
From:  ubports/messaging-app #176

Dear all,

There is no SWYPE keyboard available. From my user's side that could be an enhancement.
What about developpers' side? ;)

Best,

**Comment by Fuseteam** [comment]
Skeyer is a work in progress we cannot call it SWYPE call legal stuffs

**Comment by dobey** [comment]
As #119 is the previously referenced issue in messaging-app but moved to here, I'm closing this one.
