### ISSUE TITLE
No Thai keyboard

### ISSUE THREAD

**Issue by marlboro50** [ubports/keyboard-component#122]
FEATURE-REQUEST
-------------------------------------------------------------------------------------
There is no Thai keyboard sofar.
Not having a Thai keyboard means excluding a whole
nation from being able to use Ubuntu Touch.

![Thai-Keyboard-Portrait](https://user-images.githubusercontent.com/63823886/79518879-5d6dd300-807c-11ea-80ea-6ac2a01bc5e0.jpg)

![Thai-Keyboard-Landscape](https://user-images.githubusercontent.com/63823886/79518901-6ced1c00-807c-11ea-96c9-798f7b9e378f.jpg)

**Comment by Fuseteam** [comment]
@marlboro50 we need a thai speaker to create one, otherwise it could end up less than ideal

**Comment by peat-psuwit** [comment]
Actually, @marlboro50 contacted me personally about this and I suggested he file an issue. As I'm Thai, I'll probably take a look at it. However, it probably won't be the highest priority, so it might take some time.

BTW, @marlboro50, I hope you don't mind if I edit the issue and remove the boldness and exclamation marks. They won't escalate the issue, only the emotion.

**Comment by Fuseteam** [comment]
ah cool
