### ISSUE TITLE
Installing PR as in Readme fails

### ISSUE THREAD

**Issue by cibersheep** [ubports/keyboard-component#126]
Trying to install PR124 

`sudo ubports-qa install keyboard-component 124`

as in the read me
```
sudo ubports-qa install keyboard-component X

where X is the code of a merge request to this repository.
```

gives this error: `CRITICAL:ubports-qa:Jenkins build not found`

Workaround:
`sudo ubports-qa install PR-124` works correctly

**Comment by Fuseteam** [comment]
appearently one needs to prepend it with `ubports/`
so it becomes
`sudo ubports-qa install ubports/keyboard-component 124`
it makes me wonder if ubports-qa should automatically prepend the `ubports/` somehow
pull request #120 also includes an update to the readme

**Comment by Fuseteam** [comment]
........i completely forgot about this

**Comment by cibersheep** [comment]
Now they should work. I didn't push any new changes to my PR but I could do to test

**Comment by Fuseteam** [comment]
yeah so i recently just did `sudo ubports-qa keyboard-component 128` and it worked afaict...........

**Comment by cibersheep** [comment]
Nice. Then I'll close this and if I find it failing again I'll reopen the issue.
Thanks

**Comment by cibersheep** [comment]
Confirmed (just for posterity) that is working as expected
