### ISSUE TITLE
No makefile in keyboard-component

### ISSUE THREAD

**Issue by adrmzz** [ubports/keyboard-component#127]
According to the [README.md](https://github.com/ubports/keyboard-component) in ubports/keyboard-component, predictive models are based on databases generated from a corpus. Databases (apparently, sets of uni-, bi- and tri-grams) are created «by running "make lang_db_$lc" within the plugin's "src" directory», but there are no makefiles in that directory.

**Comment by Elleo** [comment]
You just need to run qmake first, that creates the Makefile from the Qt project file (.pro)

**Comment by adrmzz** [comment]
It worked, after installing qt5-default qt5-qmake qt5-qmake-bin, maliit-framework-dev, pkg-config and presage. Thanks!

**Comment by adrmzz** [comment]
It worked, after installing qt5-default qt5-qmake qt5-qmake-bin, maliit-framework-dev, pkg-config and presage. Thanks!

**Comment by Fuseteam** [comment]
can we update the readme?
