### ISSUE TITLE
Change the emoji button icon to smth more understandable

### ISSUE THREAD

**Issue by Flohack74** [ubports/keyboard-component#13]
Also mentioned here https://github.com/ubports/telegram-app/issues/66 - The icon for the switch to the emoji keyboard is not very indicative - why not put a real smiley there (colorful?)

**Comment by mymike00** [comment]
![osk-emoji](https://user-images.githubusercontent.com/28359593/31225118-d46d8eda-a9d0-11e7-840f-8419a769e673.jpg)
something like this...

with these action on the language button:

- onClicked: switch keyboard to emoji one
- onLongPressed: popover (like with other key...) with other languages, focusing the one in the corner (as usual). that language should be the last language used before the actual one, imo.

![osk-emoji-pressed](https://user-images.githubusercontent.com/28359593/31226637-2b2125ce-a9d7-11e7-9ab3-fbf6cecfea11.jpg)

all images are mock-ups...

**Comment by cyberpunkedu** [comment]
Could we instead make emoji a subset of every language keyboard?
e.g. You press ?123 and have the option for emoji. or a completely new button, and shorten the space bar. 
It's very awkward to switch to a new keyboard every time, especially if you use multiple languages.

**Comment by mymike00** [comment]
wow, that could be a nice idea. my only doubt is that the spacebar could be too shorten and I hate it (for example in urls the space bar is too short for me :angry: )

**Comment by cyberpunkedu** [comment]
The new spacebar text manipulation function makes me wonder if we can assign a long press to an existing key to reach the emoji input.

For example, the language/globe key might work as:
a) short press = cycle through all added languages one by one
-- or have it pop up the language selector menu
b) long press = emoji

or vice versa.

**Comment by mymike00** [comment]
@userj that's quite similar to what I suggested

> onClicked: switch keyboard to emoji one
>
> onLongPressed: popover (like with other key...) with other languages, focusing the one in the corner (as usual). that language should be the last language used before the actual one, imo.

**Comment by cyberpunkedu** [comment]
> @userj that's quite similar to what I suggested
> 
> > onClicked: switch keyboard to emoji one
> > onLongPressed: popover (like with other key...) with other languages, focusing the one in the corner (as usual). that language should be the last language used before the actual one, imo.

Yes, you had a good suggestion :) 
Mostly just resurrecting this discussion here. 

Maybe more onLongPressed keys could be a thing. e.g. the "?123" key

Other related thoughts:
1. Another option that I've seen is swiping right/left on the space bar to switch between languages
2. Can the word suggestion area at the top be used for something else while not in the middle of typing?
3. Can the key height be reduced slightly to make more space for something?

**Comment by giiba** [comment]
I would love to have onLongPress of the ?123 bring up the number pad keyboard...

And about the keyboard height, it is something I have been earmarking resourses in thoughts of adding a setting for. It is easily changeable in:
'/usr/share/maliit/plugins/com/ubuntu/keys/key_constants.js'

Look for the line about keyboard height; edit and restart unity8. I

**Comment by cyberpunkedu** [comment]
@giiba thank you for that reference and hack!

**Comment by Fuseteam** [comment]
@giiba would `restart maliit-server` also affect it?

**Comment by Fuseteam** [comment]
#129 may end up fixing this issue

**Comment by peat-psuwit** [comment]
Migrated to GitLab
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/13
