### ISSUE TITLE
Macedonian layout

### ISSUE THREAD

**Issue by boriseto** [ubports/keyboard-component#137]
Now this isn't as much of a feature request as it is help needed to set up my laptop environment to compile a keyboard to test on my device. I've already created the layout with editing the Serbian keyboard (we use Cyrillic and there are some changes to it) and at the beginning we don't have a dictionary for autocomplete, but I would like to get the letters and layout we use out in the open for starters (also cause I want to use it as well).
Can somebody ping me how to proceed on this?
Thank you.

**Comment by Fuseteam** [comment]
you can look at #86 on how to add a layout, while you won't have autocomplete yet it is fairly easy to setup a functional keyboard layout, if you have then you can just file a pull request against this repo to make it installable via ubports-qa

**Comment by boriseto** [comment]
Well for now I'm just copying the qml files into the path for a random keyboard so I can get at least the layout correct. After that I'll look into the issue on how to create all the needed files by the defined rules.

**Comment by Fuseteam** [comment]
the layout qml files map pretty well to the [source code](https://github.com/ubports/keyboard-component/tree/xenial/plugins)

**Comment by boriseto** [comment]
Just an small FYI, I made and tested the layouts. Just need to add the other stuff and connect the files I guess. I might need a little help with that though, but some other day during the week, cause it's getting late here.

**Comment by Fuseteam** [comment]
Sure if your on telegram you can ping me up @fuseteam anytime

**Comment by Fuseteam** [comment]
this was fixed by the merger of #138

**Comment by UniversalSuperBox** [comment]
Fixed by #138 and https://gitlab.com/ubports/core/seeds/ubuntu-touch/-/merge_requests/25
