### ISSUE TITLE
Add a nub

### ISSUE THREAD

**Issue by PhoenixLandPirate** [ubports/keyboard-component#14]
Sometimes moving where the cursor in a text feild can be tedius, and inaccurate, to try and amend this, we could add a nub like in windows phone.

This would allow people to pull the nub to the left a little to move left by one character, rather then having to tap several times to try and get it right, or delete more then needed.

**Comment by Flohack74** [comment]
You mean knob?

**Comment by kwah-gh** [comment]
Currently, it is possible to swipe left right, and cursor will follow. Although, it is difficult to discover. Next to it, it is still difficult to control precisely, where cursor ends up: the user tends to tap on a location of a cursor (it might be just me, of course) to interact with it, basically obstructing the view.

Other options to consider:
* Pop-up overlay, when user taps on a location of cursor (similar to on-screen keyboards, where pressed keys are being displayed above the tapped area)
* Add cursor buttons to on-screen keyboard

**Comment by cibersheep** [comment]
From OTA3? is implemented tap and holding the space bar and moving.
@NeoTheThird this could be close, maybe?
