### ISSUE TITLE
Fatal crash when trying to autocomplete a word that contains an apostrophe

### ISSUE THREAD

**Issue by kcxt** [ubports/keyboard-component#152]
When in the messages app, or any text field with autocomplete enabled, maliit-server crashes with the following error if an available autocomplete word contains an apostrophe (`'`).
```
[DatabaseConnector] Error executing SQL: 'SELECT count FROM _1_gram WHERE word = 'can't';' on database: '/usr/share/maliit/plugins/com/ubuntu/lib/en/database_en.db' : near "t": syntax error
```
Full stack trace can be found here: https://paste.ubuntu.com/p/mv6XGnXQQ9/

I'm running Manjaro ARM on a OnePlus 6T with Linux 5.11, maliit version: `maliit-framework-git 0.99.1.r54.gee7d872c-3`

**Comment by Fuseteam** [comment]
hmmm i wonder why this happens on manjaro arm but not on ubuntu touch

**Comment by kcxt** [comment]
> hmmm i wonder why this happens on manjaro arm but not on ubuntu touch

Perhaps Manjaro ARM ships a newer version and the bug was introduced after the latest release for UBports.

**Comment by Fuseteam** [comment]
> > hmmm i wonder why this happens on manjaro arm but not on ubuntu touch
> 
> Perhaps Manjaro ARM ships a newer version and the bug was introduced after the latest release for UBports.

hmm wonder if its related to a newer qt

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/152

Sorry for your inconvenience.
