### ISSUE TITLE
Double tap in cursor mover mode is harder to trigger

### ISSUE THREAD

**Issue by kugiigi** [ubports/keyboard-component#158]
### Steps to Reproduce
1. Press and Hold the spacebar or swipe from the bottom
2. Double tap to open selection mode
3. Double tap to close selection mode

### Expected Results
Double tapping toggles selection mode reliably

### Actual Results
Double tapping doesn't toggle selection mode most of the time and it seems that you need to double tap quicker

### Additional Information
This seems to be introduced in 'OTA-16' or possibly Qt5.12 as I don't notice this issue on stable.

**Comment by kugiigi** [comment]
It seems that double click now checks where the 2 clicks/taps occurred and they should be close to each other to be detected as a double click. IIRC, this wasn't the case before and that's why I implemented a custom way of checking the distance between clicks.

It's harder to trigger double click now possibly, because something's wrong with the scaling of the distance threshold used by Qt. In my observation, double clicking via mouse is easy but not with touch.

**Comment by Fuseteam** [comment]
confirmed fixed

**Comment by dadandalive** [comment]
I confirm double tapping reliably opens and closes selection mode in Nexus 5 RC 2021-W10.
