### ISSUE TITLE
Using UT on Volla, when pressing the backspace character the keyboard vanishes

### ISSUE THREAD

**Issue by kwoot** [ubports/keyboard-component#168]
Using UT/OTA-16 on Volla, when pressing the backspace character the keyboard vanishes. Will only return after putting the cursor on a text somewhere. (Really, really annoying :-) )

**Comment by Fuseteam** [comment]
is this limited to the browser/webapps or is it any text field?

**Comment by kwoot** [comment]
Checking: I don't see this in Teleports. Not in the Morph location entry field. Not in the search field in the OpenStore app. Noit in Pure Maps. Not in Pesbuk, Not in SMS messages (contact or message field). 

I indeed see it in the Tweet Mobile app. Hm, seems it is not as much as I thought it was :-).

**Comment by Fuseteam** [comment]
cool sounds like this is the same bug as https://github.com/ubports/morph-browser/issues/468

**Comment by kwoot** [comment]
Well, I propose to close this one then and let people work on #468.
