### ISSUE TITLE
Add number bar

### ISSUE THREAD

**Issue by mymike00** [ubports/keyboard-component#18]
I wish to have something like this
![osknum](https://user-images.githubusercontent.com/28359593/31227670-fd92b7b8-a9da-11e7-85f4-2b6ccbf6f1a3.jpg)

**Comment by mymike00** [comment]
should be changed every keyboard under `plugins/`? for every language and for every type (defaul, url, url_search, and email)? or is there any program/script that generates all those qml files...?

**Comment by Flohack74** [comment]
Brian, can you try to align this with our current strategy? Sounds like an interesting plan, but also the maintenance of the keyboard is really hard for such global changes.

**Comment by mymike00** [comment]
I can do it my self, just wondering if you have a faster way then writing the same thing in all those files.
Which is your current strategy?

**Comment by Flohack74** [comment]
There is no strategy, thats why I ask Brian what we can do about this in the future. So many files for the keyboard for every language is very complicated.

**Comment by mymike00** [comment]
Ah ok. Also most of the key are the same on lots of different keyboards/languages: this new number bar would be the same in every keyboard with the same alphabet...
URLs and Email keyboards could be defined as a diff to the main keyboard as only a few buttons changes...

**Comment by bhdouglass** [comment]
I'm thinking it might make sense to make all the language keyboards into a json file or something and dynamically create the keyboards that way. That would make it easier to change the keyboard gobally since you wouldn't need to update a bunch of qml files for each change.

**Comment by mymike00** [comment]
Yeah, that would be way more faster, but also I think a sort of template in common for every language (or languages with a similar layout: a template for qwerty, one for azerty and so on...) and then every language in its json file, somehow, defines only the characters that differs from the template.
in this way, adding the numbers would be needed only in the template and will be present automatically in every language

**Comment by giiba** [comment]
Couldn't this be handled in a similar fashion to the word suggestion ribbon? An extra row of number between the keypad and ribbon could complement pretty much all input layouts, without needing to customize each one. Add an option to turn it on and off and it'd be set.

If UT wants to gain widespread support, I would argue maintaining an easy system of keyboard layout customization will enable more people to take control of their devices. The current .qml files are easy to read as someone who doesn't code regularly, and modifying them is straight forward. I think the simple and straight forward path might be best for the keyboard.

**Comment by Flohack74** [comment]
Well you have to think about that Arab numbers might not be suitable for all languages. So numbers are language-dependent and therefore need to be in the customized keyboard part, not in the common one. Its tricky to solve. The current plugin model could be improved though.

**Comment by Fuseteam** [comment]
add to the fact that some languages, like japanese, have a custom keyboard layout

**Comment by UniversalSuperBox** [comment]
They do, but adding a single global number row to the existing Western layouts would reduce the work maintaining the row in the future while making many people happy. It would require changing each layout but not as much work as replacing the plug in loading system.

**Comment by mymike00** [comment]
@UniversalSuperBox  is there a Western layout? I couldn't find it, do you mind pointing me its path?

**Comment by UniversalSuperBox** [comment]
All of the Latin-type layouts are Western. "The existing Western layouts" meaning all of them except those which use a different number format.

**Comment by mymike00** [comment]
Yeah, I was wondering if there is a file with the Western template/layout inherited by all those kind of languages, so that the number bar can be added in that template/layout

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/18

Sorry for your inconvenience.
