### ISSUE TITLE
Pressing space missing vibration

### ISSUE THREAD

**Issue by mauricioduarte01** [ubports/keyboard-component#19]
hello,

I want to report a strange behavior when typing and tapping the keyboard **space** the vibration doesnt work. It does work when pressing the rest of the keys.

Thank you.

Edit: Nexus 5 RC 9

**Comment by Fuseteam** [comment]
should this issue be closed?

**Comment by UniversalSuperBox** [comment]
Whoops, yes. Closed by https://github.com/ubports/keyboard-component/pull/68
