### ISSUE TITLE
Picked suggestion overwrites some previous character

### ISSUE THREAD

**Issue by mardy** [ubports/keyboard-component#2]
If I type

> (diff

and then I pick "difficult" from the list of suggestions, the initial "(" is lost. Same happens for "#".

Elleo gave me a hint on where the problem could be, so I'll try to fix this myself.

**Comment by Flohack74** [comment]
Ok let me set up the repo for that, would be glad to accept any PR :)

**Comment by mardy** [comment]
Fixed.
