### ISSUE TITLE
Ghost keyboard also for selections

### ISSUE THREAD

**Issue by mymike00** [ubports/keyboard-component#20]
Would be very nice if the ghost keyboard (long pressed space bar) could appear also when a text is select so moving the limits of the selection would be more precisely.
Maybe the keyboard could be split in two: left for first cursor and right for the second one.
Another thing I thought is the ghost keyboard could remain until I press the space key, because selecting text could take more time imo...
hoping I explained enough well... ;)

**Comment by kugiigi** [comment]
My current branch has a similar implementation although you can't control the left and right cursor when selecting.
https://github.com/kugiigi/keyboard-component/tree/xenial_-_advanced

It's not PR-ready yet but hopefully I'll have the time soon.
