### ISSUE TITLE
Norwegian OSK layout incorrectly identified as "Norsk Bokmål" when it should be just "Norsk"

### ISSUE THREAD

**Issue by ctsrc** [ubports/keyboard-component#38]
Bokmål and Nynorsk are two different official written standards used in Norway, but they both use the same alphabet and the same keyboard layout.

The correct name for the Norwegian keyboard layout is "Norsk".

"Norsk" means Norwegian in Norwegian.

**Comment by NeoTheThird** [comment]
I guess that's because of the auto-correction and spelling. How different are the languages?

**Comment by Flohack74** [comment]
Probably this comes from Unicode tables, all that is taken from upstream Ubuntu. Do you see the same on desktop 16.04?

**Comment by Flohack74** [comment]
@mariogrip you would be the perfect match to solve this :D

**Comment by NeoTheThird** [comment]
Blindly changing the name is the worng approach. Again:

> I guess that's because of the auto-correction and spelling. How different are the languages?

If the spelling is really different (and from my understanding it is), the naming is correct.

**Comment by ctsrc** [comment]
Yeah my bad I did not consider the fact that the OSK would be responsible for spelling but it is of course.
