### ISSUE TITLE
New keyboard layouts did not land in devel

### ISSUE THREAD

**Issue by Flohack74** [ubports/keyboard-component#43]
Despite being added in the normal way, the keyboards for Turkish, Swiss French and Bulgarian did not land in the 16.04/devel nightlies.

**Comment by NeoTheThird** [comment]
Turkish and swiss-french are there, bulgarian i'm not sure, but it's tracked in https://github.com/ubports/ubuntu-touch/issues/583. Should we maybe close this issue?

**Comment by Flohack74** [comment]
Yes we close...
