### ISSUE TITLE
Add an option to slightly modify keyboard layout - e.g. from QWERTZ to QWERTY

### ISSUE THREAD

**Issue by zubozrout** [ubports/keyboard-component#45]
Hi,
I've been trying to figure out how to add a new layout for my language, as the only available Czech QWERTZ layout is a bit too unpleasant for me, and it seems that currently creating a completely new layout is required duplicating all the language files even if I just need to swap two characters (Y and Z).

So I wonder, would it be perhaps possible to update LanguageMenu like [this](https://github.com/ubports/keyboard-component/files/2116302/LanguageMenu.qml.txt) adding ListView to the po-pup component where alternate layouts could be selected and if triggered each language QML file in plugins/language/qml could do something like this:

```
	Component.onCompleted: {
		languageMenu.allowAlternateLayouts([
			{
				name: "qwertz"
				action: function() {
					setLayout("qwertz");
				}
			},
			{
				name: "qwerty"
				action: function() {
					setLayout("qwerty");
				}
			}
		]);
		
		setLayout(usedLayout || null);
	}
```
[Keyboard_cs.qml](https://github.com/ubports/keyboard-component/files/2116338/Keyboard_cs.qml.txt)

Of course things like saving the set value, and retaining it in between different layouts (url/email/search/normal) would have to be resolved and what's more it would be great if this could be selected from within the System Setting app but I am afraid a lot more radical change would be needed for that.

I would love to create a QWERTY layout for Czech but it feels bad to duplicate the whole structure for it again.

I am sure there are way better ways to deal with this though.

**Comment by zubozrout** [comment]
Well, the above idea is not a good one. It would actually be better to just update the keyboard code to allow setting qml files for single language ... so e.g. choosing from this in the same directory:
Keyboard_cs.qml
Keyboard_cs_qwerty.qml
depending upon the selected layout. And then - ideally - the settings for this should be present in the Settings app, but that would require quite a lot of changes I am afraid :(.

**Comment by Fuseteam** [comment]
there is actually a way to set multiple layouts for one language but it will require quite a bit of work
the ground work is somewhat there with the symbols layout; i.e. all languages have two layouts: the character layout and [the symbol layout](https://github.com/ubports/keyboard-component/blob/xenial/qml/languages/Keyboard_symbols.qml). it is the same symbol, layout that is available from all the other layouts.
this will need [some changes](https://github.com/ubports/keyboard-component/pull/129/files#diff-e11320fc83043f8abc4169c8997df5f48b7309b61f0330f1673aafa61b115eab) in [KeyboardContainer](https://github.com/ubports/keyboard-component/blob/xenial/qml/KeyboardContainer.qml) and a way to select the layout and language separately

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/45

Sorry for your inconvenience.
