### ISSUE TITLE
instructions for setting up, building and testing the project

### ISSUE THREAD

**Issue by helguson** [ubports/keyboard-component#46]
### problem
I'd like to add an on-screen keyboard layout for an additional language but until now I am not able to compile nor to test the current state of the repo.

So far I tried to
- find the missing packages that qtcreator lists to me but still there are some missing
- use crossbuilder but it ran into problems itself

Still I don't know the intended way of doing this and what I try is also not working. So this situation is quite ... frustating.

### proposal
extend the readme 
- either by instructions on setting up the project for development, building as well as testing it
- or by references that explain those points

**Comment by Flohack74** [comment]
Hmm while I cant help with docs you should definitely look at the other keyboards that were added: https://github.com/ubports/keyboard-component/pulls?q=is%3Apr+is%3Aclosed - you will find what needs to be done there.
