### ISSUE TITLE
Keyboard as trackpad stay on longer

### ISSUE THREAD

**Issue by PhoenixLandPirate** [ubports/keyboard-component#50]
## Steps to reproduce

1. Hold space down
2. Let go and put your thumb on top of the keyboard to pull the cursor down
3. Done 

## Expected behavoir

The trackpad stays on and the cursor gets pulled down

## Actual behavior

The trackpad turns off and turns into a keyboard quickly

## additional information

Either there should be a button to turn it off, or it should stay on for a specific amount of time.

Theres options such as tapping the keyboard or multigesture, but they may be better for adding new features such as tapping to start the selection tool to make it easier to copy and paste specific areas of writing, far easier.

**Comment by Fuseteam** [comment]
that way tap and hold keeps the "trackpad" mode/advance mode on? hmm

**Comment by Fuseteam** [comment]
this seems solved by cursor mode tho the space swipe proposal still sounds interesting :p

**Comment by Fuseteam** [comment]
@PhoenixLandPirate is this still an issue? (tho space swipe still sounds interesting)

**Comment by kugiigi** [comment]
This mode stays a lot longer now since there's a done button. Perhaps this can be closed?

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/50

Sorry for your inconvenience.
