### ISSUE TITLE
enhancement: Need "paste" button

### ISSUE THREAD

**Issue by idekovets** [ubports/keyboard-component#52]
Sometimes (ex. in Morph Browser) i have problem with copy/paste. Need "copy/paste" button on keyboard. Like these:
![default](https://user-images.githubusercontent.com/41849731/48706591-c47c2380-ec0d-11e8-94db-79f4b6fccaee.png)

Thanks!

**Comment by kugiigi** [comment]
My current branch has this button.
https://github.com/kugiigi/keyboard-component/tree/xenial_-_advanced

I haven't made it PR-ready but let's see how it goes :wink:

**Comment by Fuseteam** [comment]
the branch has been merged :p

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/keyboard-component/pull/78
