### ISSUE TITLE
unable to build keyboard-component with crossbuilder

### ISSUE THREAD

**Issue by Danfro** [ubports/keyboard-component#59]
I am using BQ E5 with RC 16.04 2018-W51.
Fresh install of Ubuntu 18.04, installed lxd as deb, not snap.
Flashed my phone recently with RC 16.04 2018-W51, and earlier RC 16.04 2018-W48.

**Steps to reproduce**
- clone the repo xenial branch i.e. by running
`git clone --single-branch --branch xenial https://github.com/ubports/keyboard-component.git`
- download and install [crossbuilder](https://github.com/ubports/crossbuilder) as described [here](http://docs.ubports.com/en/latest/systemdev/testing-locally.html#cross-building-with-crossbuilder)
- plug in your phone, developer mode enabled
- run crossbuilder
`crossbuilder --password='yourpassword'`
- reboot phone

**expected behavior:**
the keyboard is working

**actual behavior:**
the number keyboard at the login screen does show up without numbers (screenshot below), therefore I am not able to log into my phone --> ubport-installer is your friend, just flash your phone and it works again ;-)
Before OTA 6 with master branch the keyboard would show up blank.

It does seem to build a 15.04 deb (terminal output line 1701). That sort of matches the line (terminal output line 10):
> dpkg-buildpackage: source version 0.100+15.04+ubportslocal~1545468642

The terminal output is here:
[Terminal-output 2018-12-22.txt](https://github.com/ubports/keyboard-component/files/2705190/Terminal-output.2018-12-22.txt)

Screenshot of disabled keyboard after reboot:

![screenshot20181220_180218264](https://user-images.githubusercontent.com/37637312/50372378-dfa3cf80-05cd-11e9-91f2-b1cf362a3d3e.png)

**Comment by mattbel10** [comment]
I can confirm I had the same issue, for the same keyboard package but on a different phone (Meizu Pro5). I started a thread about Crossbuilder in the Forum and it ends with the same experience you got at reboot. Please check: https://forums.ubports.com/topic/1516/howto-contributing-to-app-development-with-crossbuilder/51

**Comment by helguson** [comment]
PC: 
ubuntu 16.04 LTS

Device:
bq aquaris E4.5

ubuntu touch:
Channel:  stable
Build: 16.04 (OTA-6)

keyboard-component:
branch: xenial

crossbuilder:
branch: master

I have this problem, too.

**Comment by mariogrip** [comment]
Humm, it seems to be building the correct ones, but only installs some of the packages

```
The following packages will be REMOVED:
  ubuntu-keyboard ubuntu-keyboard-arabic ubuntu-keyboard-azerbaijani
  ubuntu-keyboard-bosnian ubuntu-keyboard-bulgarian ubuntu-keyboard-catalan
  ubuntu-keyboard-chinese-chewing ubuntu-keyboard-chinese-pinyin
  ubuntu-keyboard-croatian ubuntu-keyboard-czech ubuntu-keyboard-danish
  ubuntu-keyboard-dutch ubuntu-keyboard-emoji ubuntu-keyboard-english
  ubuntu-keyboard-finnish ubuntu-keyboard-french ubuntu-keyboard-german
  ubuntu-keyboard-greek ubuntu-keyboard-hebrew ubuntu-keyboard-hungarian
  ubuntu-keyboard-icelandic ubuntu-keyboard-italian ubuntu-keyboard-japanese
  ubuntu-keyboard-korean ubuntu-keyboard-latvian
  ubuntu-keyboard-norwegian-bokmal ubuntu-keyboard-polish
  ubuntu-keyboard-portuguese ubuntu-keyboard-romanian ubuntu-keyboard-russian
  ubuntu-keyboard-scottish-gaelic ubuntu-keyboard-serbian
  ubuntu-keyboard-slovenian ubuntu-keyboard-spanish ubuntu-keyboard-swedish
  ubuntu-keyboard-swiss-french ubuntu-keyboard-turkish
  ubuntu-keyboard-ukrainian ubuntu-touch
```

**Comment by mariogrip** [comment]
Pinging @mardy, any ideas?

**Comment by helguson** [comment]
The `maliit-server` (which somehow handles the keyboard) reports that it cannot find the shared library for the keyboard.

![grafik](https://user-images.githubusercontent.com/3305305/50538809-fe7a0700-0b75-11e9-802d-bc8a177d31a6.png)

**Comment by mariogrip** [comment]
> The `maliit-server` (which somehow handles the keyboard) reports that it cannot find the shared library for the keyboard.
> 
> ![grafik](https://user-images.githubusercontent.com/3305305/50538809-fe7a0700-0b75-11e9-802d-bc8a177d31a6.png)

yeah that seems to be because it does not install all the debs

**Comment by dobey** [comment]
> Humm, it seems to be building the correct ones, but only installs some of the packages
> 
> ```
> The following packages will be REMOVED:
>   ubuntu-keyboard ... ubuntu-touch
> ```

What actually got installed here? This looks like _all_ the keyboard packages were removed, including the main package, as well as causing the ubuntu-touch metapackage to be removed. So what happened exactly?

**Comment by mymike00** [comment]
For testing changes on your device, try `crosbbuilder --no-debs`, it should work to build keyboard.
Read more at ubports/crossbuilder#16

**Comment by Fuseteam** [comment]
oof just when i was wondering how to use crossbuilder to test keyboard fixes

**Comment by Flohack74** [comment]
Is this still an issue?

**Comment by mymike00** [comment]
I will try later, long time since I used crossbuilder actually...

**Comment by mymike00** [comment]
I tried building this and it went all good. I can't deploy on phone cause my usb port is broken, but I remember `crosbbuilder --no-debs` working to install on phone. so imho it can be closed

**Comment by Fuseteam** [comment]
hmmm guess i need to try it on my phone before this gets closed, just in case

**Comment by Fuseteam** [comment]
i never managed to test this lolrip

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/59

Sorry for your inconvenience.
