### ISSUE TITLE
Swiss-French keyboard layout does not load

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/keyboard-component#60]
When the Swiss-French keyboard layout is selected in the keyboard and loaded, the keyboard goes all-white. The following appears in the logs.

```
WARNING: file:///usr/share/maliit/plugins/com/ubuntu/lib/fr-ch/Keyboard_fr-ch.qml:51:48: Expected token `,'
CRITICAL: Couldn't find word engine plugin for  "fr-ch"
```

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/keyboard-component/pull/61

**Comment by Ingo-FP-Angel** [comment]
Device: FP2
Channel: RC
Version: 2018-W01

I cannot reproduce the issue, i.e. the fix works.

**Comment by advocatux** [comment]
Device: Nexus 5 (hammerhead)
Channel: RC
Version: `2018-W01` (_really_ `2019-W01`)

Fix works
