### ISSUE TITLE
Japanese keyboard layout does not honor theme settings

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/keyboard-component#62]
When a non-default theme for the on-screen keyboard is selected, the Japanese keyboard layout does not honor all of the color settings. The flickable keys remain white as in Ambience.

![image](https://user-images.githubusercontent.com/21966173/50575839-21512900-0dcb-11e9-8c32-376cf07a3d0f.png)

**Comment by kugiigi** [comment]
Not sure why this is still open?
Seems to be fixed on stable although not yet in edge.
