### ISSUE TITLE
Should opaque keyboard set to solid color show boxes below individual keys?

### ISSUE THREAD

**Issue by zubozrout** [ubports/keyboard-component#63]
Hi,
I am not 100% sure this is a bug bug I'd expect if you set a solid color theme for a keyboard component it should stay solid and should not display every rectangle box below each key.

In practice this means that if you make the keyboard opaque it is no longer solid as the theme claims.

**Comment by zubozrout** [comment]
I would expect "Just Dark" theme to be just dark and not almost "Suru Dark". The same can be seen with "Just White" and "Just Grey".
![screenshot20190109_185341010](https://user-images.githubusercontent.com/3088349/50918281-1425e100-1440-11e9-9e95-153bef69a384.png)
![screenshot20190109_185408758](https://user-images.githubusercontent.com/3088349/50918283-14be7780-1440-11e9-82ba-e4b85429b791.png)

**Comment by kugiigi** [comment]
I think this is a valid bug. Not sure why the transparency is being applied differently in the background and each key. Let's see if this can be easily fixed :smile:

**Comment by zubozrout** [comment]
Well, I haven't looked at the code but suspect it is because the keys as well as the whole keyboard background rectangle have each set opacity to a certain value. What it would require is for the keys to be 100% opaque (fully transparent) - which could also work with a non transparent keyboard setting. Not sure however of this is doable for selected themes only since this would not be applicable to other themes where individual keys should have a visible box.

**Comment by kugiigi** [comment]
Do you have a way to check the behavior before the themes landed?
Is it the same? the keys seems to be always more opaque than the background.

**Comment by zubozrout** [comment]
For the default theme this was the same IIRC. What I am saying is that for Just Dark, Grey, White themes this should ideally stay solid (just "the selected color").

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/63

Sorry for your inconvenience.
