### ISSUE TITLE
[FEATURE REQUEST] Settings for disabling key magnifier

### ISSUE THREAD

**Issue by kugiigi** [ubports/keyboard-component#65]
### Description
This is actually an idea from one of the guys the TG supergroup and I think it makes sense.
There should be a way to disable the key magnifier in the OSK.

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/keyboard-component/pull/66

Notes for QA:

The key magnifier is the popup of the letter or symbol you press. You can now turn it off by going to System Settings > Language & Text > Key Magnifier.

**Comment by PJK2011** [comment]
Working fine on my Nexus 5 hammerhead on OTA-10 rc ver 54 image 2019-W32.

**Comment by jezek** [comment]
FP2 (2019-W32) - Working. Key magnifier can be turned on/off in Language & Text settings.

**Comment by Marzal** [comment]
Hammerhead (2019-W32) - Working without side effects.
