### ISSUE TITLE
Editing text in WebApps and in Web browser gets tricky with suggestions

### ISSUE THREAD

**Issue by zubozrout** [ubports/keyboard-component#7]
Hello,
if I insert text into a text input field in a web browser or a web app (eg. Google search) the suggestion engine may lead to some unwanted behavior issues.

So for example if I insert something like "Hello World" the last word "World" is underlined as I have text suggestions turned on. Then if I put my cursor let's say right after the word "Hello" and then type in anything ... (eg. space) the underlined word "World" gets inserted right after the word "Hello" and then the space is inserted after it. So I end up with "HelloWorld  World".

This is especially unpleasant when filling in my credit card info when paying something online as this gets preserved even when switched to a different field. So I first type in my credit card number and since the number is underlined if I click to the next field and start typing in anything my card number is duplicated in that field and I have to delete it all in that second field and start typing again.

I have reported this some time ago in Launchpad but it was too late for it to get fixed apparently: https://bugs.launchpad.net/ubuntu/+source/ubuntu-keyboard/+bug/1648599

**Comment by Stefano0101** [comment]
this shouldn't be closed as it's still happening and for a quite a long time now
Turbo/15.04/ stable or rc 
When I type in some web forms, tables, fields, sometimes the last word/charakter/number typed in last is copied to the next one upon moving the cursor and starting to type.
It doesn't happen always, that's why I found it strange. There might be even a security concern while doing internet banking and typing in passwords etc. as it remembers the last word/number/character.


Any logs needed?

**Comment by NeoTheThird** [comment]
@Stefano0101 it's not closed, it was just referenced in another issue which is closed. This one is still open.

**Comment by balcy** [comment]
for reference: https://bugs.launchpad.net/oxide/+bug/1416460

**Comment by NeoTheThird** [comment]
Should be fixed in https://github.com/ubports/oxide/pull/2 thanks to @balcy.

**Comment by balcy** [comment]
Hi, would be great if this can land in OTA4 
cheers, Chris

**Comment by Flohack74** [comment]
This fix seems not to land in the nightly devel images. Can we please check oxide CI @mariogrip

**Comment by balcy** [comment]
Is that source package used for building oxide on xenial ? https://source.ubports.com/oxide/oxide-qt_1.19.8~git1519582507.b2f1acf.orig.tar.xz
the fix is included there
