### ISSUE TITLE
Space is not added after word suggestion if autocorrect is disabled

### ISSUE THREAD

**Issue by dieharddan** [ubports/keyboard-component#71]
Automatically add a space after choosing a suggested word

**Comment by giiba** [comment]
Yes!

**Comment by Fuseteam** [comment]
how should this be done?

**Comment by Flohack74** [comment]
If you click on a word, add a space in the string that is sent to the app. Easy :)

**Comment by Fuseteam** [comment]
in wordribbon.qml?

**Comment by UniversalSuperBox** [comment]
This doesn't seem right. When using the English keyboard, open a new note in Reminders (called Notes on-device). Start typing "Test," by typing "Tes". Tap "Test" in the word ribbon. A space is added after the word.

Is this a problem specific to other languages or in certain apps?

**Comment by Fuseteam** [comment]
i cannot reproduce that @UniversalSuperBox
no space is added for me under the english keyboard in the notes app

**Comment by UniversalSuperBox** [comment]
Hmm, how are your settings set on Language & Text?

![screenshot20190901_192626573](https://user-images.githubusercontent.com/21966173/64084213-98d6af80-ccee-11e9-9b2f-ebb78bb7a83c.png)

**Comment by UniversalSuperBox** [comment]
Aha. It's autocorrect. If Auto correction is turned off, no space is added.

**Comment by Fuseteam** [comment]
crud autocorrect did not think of that :<

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/71

Sorry for your inconvenience.
