### ISSUE TITLE
autoCapitalization is activated also after `:`

### ISSUE THREAD

**Issue by mymike00** [ubports/keyboard-component#97]
### Steps to reproduce

set true autoCapitalization from system-settings (or `gsettings set com.canonical.keyboard.maliit auto-capitalization true` if you prefer).
Start typing and press the `:` char followed by a space

### Expected behavior

I'd expect to be able to continue typing the next word without a capital letter

### Actual behavior

autoCaps is triggered after `:` and the next word will automatically start with a capital letter (which shouldn't happen in western layouts imho)

If this issue needs to be fixed, I'd like to work on this, just I wanted to know your opinion about this before start working

**Comment by Flohack74** [comment]
Well thats a bit questionable in my opinion. In German for example its perefctly fine to have a capital letter after a : ... Why do you think this is generalizable across all languages?

**Comment by Flohack74** [comment]
Just reading grammar rules now for English and German - its a mess! There are various cases when either this or that is correct :)

**Comment by mymike00** [comment]
Oh, so this is language dependent... I didn't think about it...
for Italian it should not trigger autoCaps btw...
tested English keyboard on a samsung phone: after `:` autoCaps isn't triggered as well...

**Comment by Flohack74** [comment]
I would bring this up with UBLangs group first ;)

**Comment by mymike00** [comment]
Sure! can you also share me the link/invite me there? i'm afraid I'm not there...

**Comment by UniversalSuperBox** [comment]
I've made a post in the forum asking people to give us comma rules in their language: https://forums.ubports.com/topic/3305/capitalization-after-a-colon-what-does-your-language-use

Hopefully that will settle this and determine the merge of #101. :D
